{% set name = "Directory-Tree" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rahulbordoloi/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ca4639595827fa8398ef424c6050b86069decee34953c768b761f8edb0e3ba1a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - directory_tree
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rahulbordoloi/Directory-Tree/
  summary: Python Utility Package that displays out the Tree Structure of a Particular Directory.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
